<template>
    <div class="request-poster">
        <vm-request-editor></vm-request-editor>
        <vm-response-viewer></vm-response-viewer>
    </div>
</template>

<script>
    import $ from 'jquery'
    import _ from 'lodash'

    import vmRequestEditor from './request-editor/request-editor.vue'
    import vmResponseViewer from './response-viewer/response-viewer.vue'

    import RandExp from 'randexp'

    import {scheduleSending} from '../../vuex/actions.js'

    import requestEditorData from './request-editor/request-editor-data.js'

    export default {
        components: {
            vmRequestEditor,
            vmResponseViewer,
        },
        data: () => requestEditorData,
        methods: {
            refresh (){
                this.request = _.cloneDeep(this.currentRequest)
                this.getCurrentRequestRoute()
            },

            /**
             * Ask laravel what route are we dealing with, if any.
             */
            getCurrentRequestRoute () {
                this.setInfoError(null)
                let headers = _.cloneDeep(this.currentRequest.headers)
                let wheres = _.cloneDeep(this.currentRequest.wheres)

                let request = this.currentRequest
                let path = this.request.path

                // Process routes that have leading slash.
                path = path === '/' ? path : '/' + path

                // Fill path template with random strings generated by regexp where
                for (let index in wheres) {
                    let mocker = new RandExp(new RegExp(wheres[index]))
                    let dummy = new RegExp('{' + index + '}', 'g')

                    path = path.replace(dummy, mocker.gen())
                }

                headers.push({key: 'X-Api-Tester', value: 'route-info'})

                this.$api.ajax(request.method, path, request.body, headers)
                    .done((response) => {
                        let route = response.data
                        this.setCurrentRoute(route)
                        this.setResponse(null)
                    })
                    .fail((xhr, status, error) => {
                        data = xhr.responseText
                        try {
                            data = JSON.parse(data)
                        } catch (e) {}
                        let response = {
                            data,
                            isJson: typeof data !== 'string',
                            headers: xhr.getAllResponseHeaders(),
                        }

                        this.setViewerMode('preview')

                        if(this.infoMode === 'request'){
                            this.setCurrentRoute(null)
                        }

                        this.setInfoError(response)
                        this.setEditorMode('info')
                    })
            },
            send (){
                this.setCurrentRequest(this.request)
                this.setIsSending(true)
                let path = this.request.path

                let request = this.request
                // Process routes that have leading slash.
                path = path === '/' ? path : '/' + path

                let headers = _.cloneDeep(this.request.headers)
                headers.push({key: 'X-Api-Tester', value: 'catch-redirect'})

                this.getResult(request.method, path, request.body, headers)
            },

            followRedirect(data, redirects, headers){
                redirects.push(data)
                this.getResult('GET', data.location, null, headers, redirects)
            },

            getResult(method, path, body, headers, redirects = []){
                this.$api.ajax(method, path, body, headers)
                        .always(function (dataOrXHR, status, XHROrError) {
                                    // NOTE Jquery ajax is sometimes not quite sane.

                                    let xhr

                                    if (dataOrXHR && dataOrXHR.hasOwnProperty('responseText')) {
                                        xhr = dataOrXHR
                                    } else {
                                        xhr = XHROrError
                                    }

                                    let data = xhr.responseText

                                    try {
                                        data = JSON.parse(data)
                                    } catch (e) {}

                                    if(xhr.getResponseHeader('X-Api-Tester') === 'redirect'){
                                        this.followRedirect(data.data, redirects, headers);

                                        return
                                    }

                                    let response = {
                                        data,
                                        isJson: typeof data !== 'string',
                                        headers: xhr.getAllResponseHeaders(),
                                        redirects: redirects
                                    }

                                    this.setResponse(response)
                                    this.setIsSending(false)
                                }
                        )
            }


        },
        ready (){
            this.refresh()
        },
        vuex: {
            getters: {
                history: state => state.history,
                currentRequest: state => state.currentRequest,
                sendingIsScheduled: state => state.requestEditor.sendingIsScheduled,
                infoMode:(state) => state.infoMode,
            },
            actions: {
                scheduleSending,
                setInfoError: ({dispatch}, bool) => dispatch('SET_INFO_ERROR', bool),
                setResponse: ({dispatch}, response) => dispatch('SET_RESPONSE', response),
                setCurrentRoute: ({dispatch}, route) => dispatch('SET_CURRENT_ROUTE', route),
                setCurrentRequest: ({dispatch}, route) => dispatch('SET_CURRENT_REQUEST', route),
                setIsSending: ({dispatch}, sending) => dispatch('SET_REQUEST_IS_SENDING', sending),
                setViewerMode: ({dispatch}, mode) => dispatch('SET_VIEWER_MODE', mode),
                setEditorMode: ({dispatch}, mode) => dispatch('SET_EDITOR_MODE', mode),
            },
        },
        watch: {
            currentRequest(){
                this.refresh()
            },
            // Kinda vuex event
            sendingIsScheduled (isScheduled){
                if (isScheduled) {
                    this.send()
                    this.scheduleSending(false)
                }
            },
        },
    }
</script>

<style scoped>

</style>
